[package]
name = "interpreter-in-rust"
version = "0.1.0"
authors = ["Piotr Pszczółkowski <piotr@beesoft.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2"
